# This software is open source software available under the BSD-3 license.
#
# Copyright (c) 2022 Triad National Security, LLC. All rights reserved.
# Copyright (c) 2022 Lawrence Livermore National Security, LLC. All rights
# reserved.
# Copyright (c) 2022 UT-Battelle, LLC. All rights reserved.
#
# Additional copyright and license information can be found in the LICENSE file
# distributed with this code, or at
# https://raw.githubusercontent.com/MPAS-Dev/MPAS-Analysis/main/LICENSE

from mpas_analysis.shared import AnalysisTask

from mpas_analysis.shared.climatology import RemapMpasClimatologySubtask

from mpas_analysis.shared.plot import PlotClimatologyMapSubtask


class ClimatologyMapSeaIceAerosolImpurities(AnalysisTask):
    """
    An analysis task for plotting seasonal climatologies of sea-ice dust and
    black carbon burden fields in polar stereographic projections.
    """

    # Authors
    # -------
    # Generated by Copilot adaptation

    def __init__(self, config, mpas_climatology_task, hemisphere,
                 control_config=None, impurity_variables=None):
        """
        Construct the analysis task.

        Parameters
        ----------
        config : tranche.Tranche
            Configuration options

        mpas_climatology_task : ``MpasClimatologyTask``
            The task that produced the climatology to be remapped and plotted

        hemisphere : {'NH', 'SH'}
            The hemisphere to plot

        control_config : tranche.Tranche, optional
            Configuration options for a control run (if any)
        """
        task_name = f'climatologyMapSeaIceAerosolImpurities{hemisphere}'

        tags = ['climatology', 'horizontalMap', 'seaiceAerosols',
            'seaIceAerosols', 'publicObs',
            'seaIceImpurities', 'seaiceImpurities',
            'climatologyMapSeaIceImpurities',
            'climatologyMapSeaiceImpurities']
        if hemisphere == 'NH':
            tags.append('arctic')
        else:
            tags.append('antarctic')

        super().__init__(config=config, taskName=task_name,
                         componentName='seaIce', tags=tags)

        section_name = self.taskName
        hemisphere_long = 'Northern' if hemisphere == 'NH' else 'Southern'
        parent_section = 'climatologyMapSeaIceImpurities'

        if config.has_option(parent_section, 'seasons'):
            seasons = config.getexpression(parent_section, 'seasons')
        else:
            seasons = config.getexpression(section_name, 'seasons')
        if len(seasons) == 0:
            raise ValueError(f'config section {section_name} does not contain '
                             'valid list of seasons')

        if config.has_option(parent_section, 'comparisonGrids'):
            comparison_grid_names = config.getexpression(
                parent_section, 'comparisonGrids')
        else:
            comparison_grid_names = config.getexpression(
                section_name, 'comparisonGrids')
        if len(comparison_grid_names) == 0:
            raise ValueError(f'config section {section_name} does not contain '
                             'valid list of comparison grids')

        grid_keyword = 'arctic' if hemisphere == 'NH' else 'antarctic'
        comparison_grid_names = [grid_name for grid_name in
                                 comparison_grid_names
                                 if grid_name.lower().startswith(grid_keyword)]
        if len(comparison_grid_names) == 0:
            raise ValueError(f'No valid {grid_keyword} comparison grids '
                             f'found in section {section_name}')

        variable_specs = [
            {'variable': 'TotalSeaIceDustSnow',
             'field': 'totalVerticalDustSnow',
             'title': 'Total dust in snow',
             'units': r'mg m$^{-2}$',
             'factor': 1.0e6,
             'config_section': 'seaIceDustImpurity'},
            {'variable': 'TotalSeaIceDustIce',
             'field': 'totalVerticalDustIce',
             'title': 'Total dust in ice',
             'units': r'mg m$^{-2}$',
             'factor': 1.0e6,
             'config_section': 'seaIceDustImpurity'},
            {'variable': 'TotalSeaIceBCSnow',
             'field': 'totalVerticalBCSnow',
             'title': 'Total BC in snow',
             'units': r'ng g$^{-1}$',
             'factor': 3.030303e6,
             'config_section': 'seaIceBCImpurity'},
            {'variable': 'TotalSeaIceBCIce',
             'field': 'totalVerticalBCIce',
             'title': 'Total BC in ice',
             'units': r'ng g$^{-1}$',
             'factor': 3.030303e6,
             'config_section': 'seaIceBCImpurity'}
        ]

        if impurity_variables is not None:
            variable_map = {spec['variable']: spec for spec in variable_specs}
            variable_specs = [variable_map[name] for name in impurity_variables
                              if name in variable_map]

        if len(variable_specs) == 0:
            raise ValueError('No valid sea-ice impurity variables selected.')

        for spec in variable_specs:
            field_name = spec['field']
            mpas_field_name = f'timeMonthly_avg_{field_name}'

            remap_climatology_subtask = RemapMpasSeaIceImpurityClimatology(
                mpas_climatology_task=mpas_climatology_task,
                parent_task=self,
                climatology_name=f'{field_name}{hemisphere}',
                variable_list=[mpas_field_name],
                comparison_grid_names=comparison_grid_names,
                seasons=seasons,
                conversion_factor=spec['factor'])

            ref_title_label = None
            ref_field_name = None
            diff_title_label = None
            if control_config is not None:
                control_run_name = control_config.get('runs', 'mainRunName')
                ref_title_label = f'Control: {control_run_name}'
                ref_field_name = mpas_field_name
                diff_title_label = 'Main - Control'

            for comparison_grid_name in comparison_grid_names:
                for season in seasons:
                    subtask_name = \
                        f'plot_{field_name}_{season}_{comparison_grid_name}'
                    subtask = PlotClimatologyMapSubtask(
                        parentTask=self, season=season,
                        comparisonGridName=comparison_grid_name,
                        remapMpasClimatologySubtask=remap_climatology_subtask,
                        remapObsClimatologySubtask=None,
                        controlConfig=control_config,
                        subtaskName=subtask_name)

                    image_caption = (
                        f'Climatology map of {hemisphere_long}-hemisphere '
                        f'{spec["title"].lower()}')

                    subtask.set_plot_info(
                        outFileLabel=f'{field_name}{hemisphere}',
                        fieldNameInTitle=spec['title'],
                        mpasFieldName=mpas_field_name,
                        refFieldName=ref_field_name,
                        refTitleLabel=ref_title_label,
                        diffTitleLabel=diff_title_label,
                        unitsLabel=spec['units'],
                        imageCaption=image_caption,
                        galleryGroup=(
                            f'Aerosol Impurities - '
                            f'{hemisphere_long}-Hemisphere'),
                        groupSubtitle=None,
                        groupLink=(
                            f'{hemisphere.lower()}_aerosol_impurities'),
                        galleryName=spec['title'],
                        configSectionName=spec['config_section'],
                        prependComparisonGrid=False)

                    self.add_subtask(subtask)


class RemapMpasSeaIceImpurityClimatology(RemapMpasClimatologySubtask):
    """
    A subtask for converting sea-ice impurity fields to requested plotting
    units after climatology masking and prior to remapping.
    """

    def __init__(self, mpas_climatology_task, parent_task, climatology_name,
                 variable_list, seasons, comparison_grid_names,
                 conversion_factor):

        super().__init__(
            mpasClimatologyTask=mpas_climatology_task,
            parentTask=parent_task,
            climatologyName=climatology_name,
            variableList=variable_list,
            comparisonGridNames=comparison_grid_names,
            seasons=seasons,
            iselValues=None,
            subtaskName=f'remap_{climatology_name}')

        self.conversion_factor = conversion_factor

    def customize_masked_climatology(self, climatology, season):
        """
        Apply a scalar conversion to the mapped variable.
        """
        climatology = super().customize_masked_climatology(climatology, season)

        variable = self.variableList[0]
        climatology[variable] = climatology[variable] * self.conversion_factor
        return climatology