# This software is open source software available under the BSD-3 license.
#
# Copyright (c) 2026 Triad National Security, LLC. All rights reserved.
# Copyright (c) 2026 Lawrence Livermore National Security, LLC. All rights
# reserved.
# Copyright (c) 2026 UT-Battelle, LLC. All rights reserved.
#
# Additional copyright and license information can be found in the LICENSE file
# distributed with this code, or at
# https://raw.githubusercontent.com/MPAS-Dev/MPAS-Analysis/main/LICENSE

import xarray as xr

from mpas_analysis.shared import AnalysisTask

from mpas_analysis.shared.climatology import RemapMpasClimatologySubtask

from mpas_analysis.shared.plot import PlotClimatologyMapSubtask


class ClimatologyMapIceFluxDust(AnalysisTask):
    """
    An analysis task for plotting maps of the iceFluxDust variable from the
    ocean component.  The class is hemisphere aware and simply uses the
    comparison grid to restrict the map to the Arctic or Antarctic.  No
    observational comparison is available.
    """

    # Authors
    # -------
    # Generated by Copilot adaptation

    def __init__(self, config, mpasClimatologyTask, hemisphere,
                 controlConfig=None):
        """
        Construct the analysis task.

        Parameters
        ----------
        config : tranche.Tranche
            Configuration options

        mpasClimatologyTask : ``MpasClimatologyTask``
            The task that produced the climatology to be remapped and plotted

        hemisphere : {'NH', 'SH'}
            Hemisphere for which to create maps.  The value is used only for
            tagging and to choose the comparison grid; the underlying
            climatology is always computed globally by the climatology task.

        controlConfig : tranche.Tranche, optional
            Configuration options for a control run (if any).  If provided,
            a difference panel (main - control) will be produced.
        """

        taskName = f'climatologyMapIceFluxDust{hemisphere}'
        fieldName = 'iceFluxDust'

        tags = ['climatology', 'horizontalMap', fieldName, 'BGC']
        if hemisphere == 'NH':
            tags.append('arctic')
        else:
            tags.append('antarctic')

        super(ClimatologyMapIceFluxDust, self).__init__(
            config=config, taskName=taskName,
            componentName='ocean',
            tags=tags)

        # MPAS variable name in the timeseries stream
        mpasFieldName = 'timeMonthly_avg_iceFluxDust'
        iselValues = None

        sectionName = taskName
        hemisphereLong = 'Northern' if hemisphere == 'NH' else 'Southern'

        # read in what seasons we want to plot
        seasons = config.getexpression(sectionName, 'seasons')
        if len(seasons) == 0:
            raise ValueError(f'config section {sectionName} does not contain '
                             'valid list of seasons')

        comparisonGridNames = config.getexpression(sectionName,
                                                   'comparisonGrids')
        if len(comparisonGridNames) == 0:
            raise ValueError(f'config section {sectionName} does not contain '
                             'valid list of comparison grids')

        # create remapper subtask that will add the variable to the
        # climatology task and perform the remapping
        remapClimatologySubtask = RemapMpasClimatologySubtask(
            mpasClimatologyTask=mpasClimatologyTask,
            parentTask=self,
            climatologyName=f'{fieldName}{hemisphere}',
            variableList=[mpasFieldName],
            comparisonGridNames=comparisonGridNames,
            seasons=seasons,
            iselValues=iselValues)

        # loop over grids and seasons to create plot subtasks
        for comparisonGridName in comparisonGridNames:
            for season in seasons:
                subtaskName = f'plot_{season}_{comparisonGridName}'
                subtask = PlotClimatologyMapSubtask(
                    parentTask=self, season=season,
                    comparisonGridName=comparisonGridName,
                    remapMpasClimatologySubtask=remapClimatologySubtask,
                    remapObsClimatologySubtask=None,
                    controlConfig=controlConfig,
                    subtaskName=subtaskName)

                refTitleLabel = None
                refFieldName = None
                diffTitleLabel = None
                if controlConfig is not None:
                    control_run_name = controlConfig.get('runs',
                                                         'mainRunName')
                    refTitleLabel = f'Control: {control_run_name}'
                    refFieldName = mpasFieldName
                    diffTitleLabel = 'Main - Control'

                subtask.set_plot_info(
                    outFileLabel=f'{fieldName}{hemisphere}',
                    fieldNameInTitle='Ice flux dust',
                    mpasFieldName=mpasFieldName,
                    refFieldName=refFieldName,
                    refTitleLabel=refTitleLabel,
                    diffTitleLabel=diffTitleLabel,
                    unitsLabel=r'kg m$^{-2}$ s$^{-1}$',
                    imageCaption=f'{hemisphereLong}-hemisphere ice flux dust',
                    galleryGroup='ice flux dust',
                    groupSubtitle=None,
                    groupLink='ice_flux_dust',
                    galleryName=None,
                    configSectionName=None)

                self.add_subtask(subtask)
